## WiSHFUL Agent config file

agent_info:
  name: 'tx'
  info: 'agent_info'
  iface: 'eth3'

modules:
  discovery:
      module : wishful_module_discovery_pyre
      class_name : PyreDiscoveryAgentModule
      kwargs: {"iface":"eth3", "groupName":"wishful_1234"}

  gnuradio:
      module : wishful_module_gnuradio
      class_name : GnuRadioModule
      interfaces : ['usrp', ]
